issuer: "http://dex.localtest.me:5556"

storage:
  type: sqlite3

web:
  http: 0.0.0.0:5556

oauth2:
  skipApprovalScreen: true

staticClients:
  - id: brink
    name: brink
    secret: brink
    redirectURIs:
      - 'http://localhost:7000/a/callback'

enablePasswordDB: true

staticPasswords:
  - email: "john@local"
    # bcrypt hash of the string "password"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "john"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
  - email: "jane@local"
    # bcrypt hash of the string "password"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "jane"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5467"
