apiVersion: v1
kind: Service
metadata:
  name: parttysh
spec:
  selector:
    service: parttysh
  ports:
    - port: 2222
      targetPort: 2222
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parttysh
spec:
  replicas: 1
  selector:
    matchLabels:
      service: parttysh
  template:
    metadata:
      labels:
        service: parttysh
    spec:
      containers:
        - image: ghcr.io/jsiebens/parttysh:latest
          name: parttysh