apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    service: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      service: postgres
  template:
    metadata:
      labels:
        service: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: foo
          image: postgres:alpine
          name: postgres